# Generated by Django 5.2 on 2025-12-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kickboxing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionplan',
            name='reason',
            field=models.TextField(blank=True, help_text='なぜこのプランを立てたのか？', verbose_name='作成意図・背景'),
        ),
        migrations.AlterField(
            model_name='actionplan',
            name='is_done',
            field=models.BooleanField(default=False, help_text=' 完了したらチェック'),
        ),
    ]
